### ISSUE TITLE
配置后没有反应，是不是更新后语法失效了呢

### ISSUE THREAD

**Issue by BradPitted** [qingmail/rime-pifu#1]
配置后没有反应，是不是更新后语法失效了呢
![1637748188187](https://user-images.githubusercontent.com/49753408/143218249-a656e7ae-c241-48c6-ac3a-f1ff21903dc2.jpg)

**Comment by qingmail** [comment]
建议重新配置，偏好设置里打开鼠须管通知，这样成功或失败会直接提示
